#:import start start

GameWidget:

<GameWidget>:
    canvas.before:
        Rectangle:
            size: self.size
            source: 'images/bg1.jpg'
    start_widget: start_widget
    perspective_point_x: self.width/2
    perspective_point_y: self.height*0.75
    StartWidget:
        id: start_widget
    Label:
        text: root.score_txt
        font_size: dp(20)
        font_name: 'fonts/Eurostile.ttf'
        pos_hint: { "center_x": 0.05, "center_y": 0.95}
        size_hint: .18, .18
