#:import menu menu

<GameWidget>:
    canvas.before:
        Rectangle:
            size: self.size
            source: 'images/bg1.jpg'
    menu_widget: menu_widget
    perspective_point_x: root.width/2
    perspective_point_y: root.height*0.75
    MenuWidget:
        id: menu_widget
    Label:
        text: root.score_txt
        font_size: dp(20)
        font_name: 'fonts/Eurostile.ttf'
        size_hint: .18, .18
        pos_hint: {"x": 0, "top": 1}
